### ISSUE TITLE
Deprecate config-SRIOV.sh

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/integration-k8s-packet#105]
[config-SRIOV.sh](https://github.com/networkservicemesh/integration-k8s-packet/blob/main/scripts/sriov/config-SRIOV.sh) is a shell script to generate an SRIOV config for cmd-forwarder-sriov.

I would suggest that we could adopt the trick being used for things like [vpphelper](https://github.com/edwarnicke/vpphelper) and generate the config ourselves in Go if one is not present.  Thus everything in config-SRIOV.sh could be incorporated into cmd-forwarder-sriov itself (I think) and we'd have no need of shell scripts.

**Comment by Bolodya1997** [comment]
SR-IOV config file has the following format:
```yaml
physicalFunctions:
  0000:01:00.0:               # 1. PCI address of SR-IOV capable NIC that we want to use with Forwarder
    pfKernelDriver: pf-driver # 2. PF kernel driver
    vfKernelDriver: vf-driver # 3. VF kernel driver
    capabilities:             # 4. List of capabilities
      - intel
      - 10G
    serviceDomains:           # 5. List of service domains
      - service.domain.1
  0000:02:00.0:
    ...
```
It is expected, that user (NSM admin) manually fills this config file, because:
1. **Problem**: We don't actually know which devices should be managed by Forwarder.
  **Solution**: We can try to use all devices except of the used by default networking.
2. **Problem**: If PF is not bounded to the kernel driver, there is totally no chance to discover what it should be (only with some special knowledge).
  **Solution**: ---
3. **Problem**: Same here for VF.
  **Solution**: ---
4. **Problem**: We don't actually know what is device capability.
  **Solution**: We probably can parse NIC description for some common words:
   ```
   Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 01)
   ```
5. **Problem**: We have totally no idea about the service domains beyond the device.
  **Solution**: ---

Such configuration can be done during the packet cluster setup with the script, because we actually know:
1. What is the device that we want to use.
2. Currently there is no `vfio-pci` driver loaded, so device is bounded to the kernel driver.
3. Any newly created VF will also be bounded to the kernel driver for the same reason (there are 2 different drivers for PF and VF).
4. What is the NIC of the host and what are the capabilities of this NIC.
5. We have some predefined service domains for the master and for the worker nodes.

So I suppose that instead of deprecating `config-SRIOV.sh` we should probably add some documentation helping user to manually create such configuration file?
